# Generated by Django 4.0 on 2022-01-30 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_dashboard_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboarduser',
            name='is_approved',
        ),
    ]
